---
title: "Overal Results"
author: "Kadir Korkmaz"
date: "January 8, 2021"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Note: This report contains only the mean value for each statistics. You can use provided links to access the detailes of a report.

## 1 MB Block Size


```{r cars, echo=FALSE}

library(knitr)

name <- c("concurrency 1","concurrency 3","concurrency 5","concurrency 7","concurrency 10")

block_propagation <- c(10.01, 10.00, 10.01, 10.01, 10.03)
ba_without_final  <- c(12.64, 12.63, 12.61, 12.63, 12.66)
ba_with_final     <- c(14.83, 14.84, 14.82, 14.89, 14.93)

dataset <- data.frame(name, block_propagation, ba_without_final,  ba_with_final )


kable(dataset)

```


### Links of Experiment Reports

[Report: block Size 1MB, Concurrency Constant 1](https://drive.google.com/file/d/1a8ihEw5rICZm8lOv2dN6mshd1PfvrMO4/view?usp=sharing)

[Report: Block Size 1MB, Concurrency Constant 3](https://drive.google.com/file/d/1n6-kcMuArgkpVHsVDF5M2BWm5T1UVUAf/view?usp=sharing)

[Report: Block Size 1MB, Concurrency Constant 5](https://drive.google.com/file/d/1BBNPuLv_jlQadaJ19uxYRf2OiEpEGAm1/view?usp=sharing)

[Report: Block Size 1MB, Concurrency Constant 7](https://drive.google.com/file/d/1GVHF7BAKsvBR4ZbgfRURq64IH4fKD66o/view?usp=sharing)

[Report: Block Size 1MB, Concurrency Constant 10](https://drive.google.com/file/d/1dRoxrb1ku_XFPe9cX37hEOd9EU_NKiVp/view?usp=sharing)




## 2 MB Block Size


```{r , echo=FALSE}

library(knitr)

name <- c("concurrency 1","concurrency 3","concurrency 5","concurrency 7","concurrency 10")

block_propagation <- c(10.01, 10.03, 10.11, 10.26, 10.44)
ba_without_final  <- c(12.63, 12.62, 12.63, 12.64, 12.67)
ba_with_final     <- c(14.81, 14.83, 14.86, 14.87, 14.91)

dataset <- data.frame(name, block_propagation, ba_without_final,  ba_with_final )


kable(dataset)

```


### Links of Experiment Reports

[Report: block Size 2MB, Concurrency Constant 1](https://drive.google.com/file/d/1wEM6K76Z9WZVz9AFmbFbpksVkGji_QFH/view?usp=sharing)

[Report: Block Size 2MB, Concurrency Constant 3](https://drive.google.com/file/d/1qQ-XG5Aai2fRt3utrTWiqbfbDW0j2MAr/view?usp=sharing)

[Report: Block Size 2MB, Concurrency Constant 5](https://drive.google.com/file/d/1CJ2KYX_jHc1-ozh6z1WcM85Ej-mLzDR2/view?usp=sharing)

[Report: Block Size 2MB, Concurrency Constant 7](https://drive.google.com/file/d/11Yih13aED2w1j_Lmd9k_UEI8MBV59l4z/view?usp=sharing)

[Report: Block Size 2MB, Concurrency Constant 10](https://drive.google.com/file/d/11K_Ato68Ku1gJ1p4FqErR2D5Ux09zLCH/view?usp=sharing)




## 4 MB Block Size


```{r , echo=FALSE}

library(knitr)

name <- c("concurrency 1","concurrency 3","concurrency 5","concurrency 7")

block_propagation <- c(10.16, 10.65, 14.15, 14.91)
ba_without_final  <- c(12.70, 12.63, 14.81, 21.87)
ba_with_final     <- c(14.89, 14.78, 17.06, 25.85)

dataset <- data.frame(name, block_propagation, ba_without_final,  ba_with_final )


kable(dataset)

```


### Links of Experiment Reports

[Report: block Size 4MB, Concurrency Constant 1](https://drive.google.com/file/d/1pTPMnFEd3Sgtpfoy_DOGnvs31VLqzdfD/view?usp=sharing)

[Report: Block Size 4MB, Concurrency Constant 3](https://drive.google.com/file/d/1YS-ZLChQBLZv5aw1xbKBplLZ71dBDfW7/view?usp=sharing)

[Report: Block Size 4MB, Concurrency Constant 5](https://drive.google.com/file/d/1ztG4CPc7qjH856qEGN_frp33Kh4voJkc/view?usp=sharing)

[Report: Block Size 4MB, Concurrency Constant 7](https://drive.google.com/file/d/1Lb7UGg7CsOy6qKLyYhueXhonIqC1pSDN/view?usp=sharing)



